openapi: 3.0.0
info:
  title: Campaign Management API
  version: 1.0.0
paths:
  /campaigns:
    post:
      summary: Create a new campaign
    get:
      summary: Retrieve all campaigns
  /campaigns/{id}:
    get:
      summary: Retrieve a specific campaign
    put:
      summary: Update a specific campaign
    delete:
      summary: Delete a specific campaign
  /campaigns/{id}/schedule:
    post:
      summary: Schedule a specific campaign
  /email-lists:
    post:
      summary: Create a new email list
    get:
      summary: Retrieve all email lists
  /email-lists/{id}:
    get:
      summary: Retrieve a specific email list
    put:
      summary: Update a specific email list
    delete:
      summary: Delete a specific email list
  /sublists:
    post:
      summary: Create a new sublist
    get:
      summary: Retrieve all sublists
  /sublists/{id}:
    get:
      summary: Retrieve a specific sublist
    put:
      summary: Update a specific sublist
    delete:
      summary: Delete a specific sublist
  /workflows:
    post:
      summary: Create a new workflow
    get:
      summary: Retrieve all workflows
  /workflows/{id}:
    get:
      summary: Retrieve a specific workflow
    put:
      summary: Update a specific workflow
    delete:
      summary: Delete a specific workflow
  /templates:
    post:
      summary: Create a new template
    get:
      summary: Retrieve all templates
  /templates/{id}:
    get:
      summary: Retrieve a specific template
    put:
      summary: Update a specific template
    delete:
      summary: Delete a specific template
  /ab-tests:
    post:
      summary: Create a new A/B test
    get:
      summary: Retrieve all A/B tests
  /ab-tests/{id}:
    get:
      summary: Retrieve a specific A/B test
    put:
      summary: Update a specific A/B test
    delete:
      summary: Delete a specific A/B test
