server:
  port: 8081

spring:
  jpa:
    show-sql: true
    hibernate:
      format-sql: true
      ddl-auto: update
  data:
    jpa:
      repositories:
        enabled: true
    rest:
      basePath: /api